In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC 
from sklearn.metrics import confusion_matrix

In [2]:
#Loading the dataset
iris=load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [3]:
# Creating feature and target variables
a = iris.data
b = iris.target

In [24]:
# Spliting the data into training and test data where test data is 30%
x_train, x_test, y_train, y_test = train_test_split(a, b, test_size = 0.3, random_state=1)

In [25]:
#Generating the SVM model with degree=3 and using Linear Kernel
c1 = SVC(kernel='linear',degree=3, random_state = 1)
# Fitting the data into the model
c1.fit(x_train,y_train)

SVC(kernel='linear', random_state=1)

In [26]:
# Predict new unseen data using the model we made
y_pred1 = c1.predict(x_test)
print(y_pred1)

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 2 2 1]


In [27]:
#Using confusion matrix to calculate model accuracy when using Linear Kernel
conf1=confusion_matrix(y_test, y_pred1)
print('Confusion Matrix','\n',conf1)
accuracy1 = float(conf1.diagonal().sum())/len(y_test)
print('\033[1m' +"\n Accuracy Of this SVM Model with Linear Kernel : ", accuracy1*100,'%')

Confusion Matrix 
 [[14  0  0]
 [ 0 18  0]
 [ 0  0 13]]

 Accuracy Of this SVM Model with Linear Kernel :  100.0 %


In [28]:
#Generating a Second SVM model with degree=3 but using RBF Kernel
c2 = SVC(kernel='rbf',degree=3, random_state = 1)
#Fitting the data into the model
c2.fit(x_train,y_train)

SVC(random_state=1)

In [29]:
# Predict new unseen data using the model we made
y_pred2 = c2.predict(x_test)
print(y_pred2)

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 2 2 1]


In [30]:
#Using confusion matrix to calculate model accuracy when using RBF Kernel 
conf2=confusion_matrix(y_test, y_pred2)
print('Confusion Matrix','\n',conf2)
accuracy2 = float(conf2.diagonal().sum())/len(y_test)
print('\033[1m' +"\n Accuracy Of this SVM Model with RBF Kernel : ", accuracy2*100,'%')

Confusion Matrix 
 [[14  0  0]
 [ 0 17  1]
 [ 0  0 13]]

 Accuracy Of this SVM Model with RBF Kernel :  97.77777777777777 %


In [31]:
#Generating the SVM model with degree=3 and using Polynomial Kernel
c3 = SVC(kernel='poly',degree=3, random_state = 1)
#Fitting the data into the model
c3.fit(x_train,y_train)

SVC(kernel='poly', random_state=1)

In [32]:
# Predict new unseen data using the model we made
y_pred3 = c3.predict(x_test)
print(y_pred3)

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 2 2 1]


In [33]:
#Using confusion matrix to calculate model accuracy when using Polynomial Kernel 
conf3=confusion_matrix(y_test, y_pred3)
print('Confusion Matrix','\n',conf3)
accuracy3 = float(conf3.diagonal().sum())/len(y_test)
print('\033[1m' +"\n Accuracy Of this SVM Model with Polynomial Kernel : ", accuracy3*100 ,'%' )

Confusion Matrix 
 [[14  0  0]
 [ 0 17  1]
 [ 0  0 13]]

 Accuracy Of this SVM Model with Polynomial Kernel :  97.77777777777777 %


<h3 align='center'>From the previous we conclude that Linear Kernel has the highest Accuracy (100%) while both Linear and RBF Kernels had the same Accuracy (97.7777%) on this dataset 